export const FETCH_USERLIST = 'FETCH_USERLIST';
export const FETCH_USERLIST_FAILED= 'FETCH_USERLIST_FAILED';

export const FETCH_FOLLOWER_LIST = 'FETCH_FOLLOWER_LIST';
export const FETCH_FOLLOWER_LIST_FAILED= 'FETCH_FOLLOWER_LIST_FAILED';
export const FETCH_REPO_LIST = 'FETCH_REPO_LIST';
export const FETCH_REPO_LIST_FAILED= 'FETCH_REPO_LIST_FAILED';